
import { Inter } from "next/font/google";
import "./globals.css";
import "@/public/css/bootstrap.min.css";
import Nabar from "./component/navbar.js";
import Providers from "@/redux/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Drink_ping",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="vi">

      <body className={inter.className}>
        
     <Providers>
     <Nabar/>
      {children}</Providers>
      <script src="https://kit.fontawesome.com/7b8b40ab0a.js" crossorigin="anonymous"></script>
      <script src="js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}